{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'odoo-mates',
    'sequence': -100,
    'summary': 'hospital management system',
    'description': """This module contains all the common features of hospital management system.""",
    'depends': ['mail','product'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/cancel_appointment_view.xml',
        'wizard/appointment_report_view.xml',
        'report/appointment_details.xml',
        'report/report.xml',
        'views/menu.xml',
        'views/patient_view.xml',
        'views/female_patient_view.xml',
        'views/appointment_view.xml',
        'views/patient_tag_view.xml',
    ],
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}